const TELAS = {
    TELA_PRINCIPAL: 'TELA_PRINCIPAL',
    TELA_CONTADOR: 'TELA_CONTADOR',
    TELA_FORMULARIO: 'TELA_FORMULARIO',
    TELA_LISTA: 'TELA_LISTA',
    TELA_LOGIN: 'TELA_LOGIN',
    TELA_NOVO_USUARIO: 'TELA_NOVO_USUARIO',
    TELA_LISTAGEM_USUARIOS: 'TELA_LISTAGEM_USUARIOS',
    TELA_DETALHES_USUARIO: 'TELA_DETALHES_USUARIO',
    
}

export default TELAS;